### ISSUE TITLE
Week 4 exercise submission

### ISSUE THREAD

**Issue by salamarche** [salamarche/DiscoverMusic#1]
@pawaitemadisoncollege exercise ready for review

What were your key learning points/takeaways?
using hibernate annotations, reviewing ORM concepts, more practice with tests.

What challenged you?
Had to fool around with the pom file for a bit. Went back and forth implementing this on the week 2 project but ended up abandoning it and working on my indie project instead. 

What problems did you solve and what resources did you use to solve them? 
I learned the hard way that the test database class (I think I got it  from the website not github) was reading in the cleandb.sql as a single line. Took me a good 20-30 minutes to figure that out and of course this is before I finished watching all the videos for the week. Aint that just the way.
Also tripped up with testing saveOrUpdate for a bit. Glad I threw that question out to slack sooner rather than later because it saved me so much time.

**Comment by pawaitemadisoncollege** [comment]
Nice job implementing hibernate in your indie project right away - this will serve you well @salamarche!  The Dao and unit tests look good!

-[ ] It looks like this is already on your radar, but just in case.... Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/salamarche/DiscoverMusic/blob/f8d26590290552fc595bbf9b9e3085d20d0ecc34/src/test/java/edu/matc/persistence/UserDaoTest.java#L87
