### ISSUE TITLE
Checkpoint 2

### ISSUE THREAD

**Issue by salamarche** [salamarche/DiscoverMusic#4]
Checkpoint 2 is ready for review  @pawaitemadisoncollege

Problem statement and app diagram are still WIP. Also expecting some changes to the database tables when I figure out how/when I'll be consuming the APIs. TIA for the feedback.

**Comment by pawaitemadisoncollege** [comment]
You've been doing a nice job implementing weekly work with in your indie project and it really shows in checkpoint 2 @salamarche!

- [ ] Is there an ERD available so that I can review the DB structure? Apologies if I simply overlooked it...
- [ ] As we chatted about last week, you should be able to do everything needed with a single generic dao. Just noting this here so I don't lose track of it!

**Comment by salamarche** [comment]
Updating checkpoint 2 to confirm that I have a single generic dao and an ERD pushed to the main branch. Thanks!
