### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by salamarche** [salamarche/DiscoverMusic#9]
Checkpoint 3 is ready for review @pawaitemadisoncollege 

FYI I originally designed the location search with three different endpoints but it preformed really poorly so I changed it to use one but those unused services are still there for that reason.  You can see it working here: http://3.140.97.66:8080/DiscoverMusic/discover. It performs really  poorly (taking upwards of 10 seconds to load) My plan to improve response time was just to reduce the number of available locations but also interested in hearing any feedback about that too.

**Comment by pawaitemadisoncollege** [comment]
Hi @salamarche -

Regarding performance - is it always pokey or once the application is used a bit does performance improve? Hibernate does have some of its own caching, it can take a while for the data to be cached.  A couple other thoughts:
1) cache the information yourself if the data won't change all that often. Would it be possible to load and store some data that is fairly static into the ServletContext (which has application scope) so that it's available for all users without a hit to the backend? 
2) limiting the data as you mentioned, works too. Is most of the filtering happening on the front end right now? Does filtering on the backend speed things up?

I was not able to test the application on aws - I think I missed my testing window! I have a feeling the server just needs a bounce...

Looking at your code - wow! You've done a lot here and it looks like you've hit the key requirements of the project (I'll need to run through the application live to be 100% sure).

- [ ] A nice thing to add would be one or more custom error pages - these can be specified in the web.xml to be shown if a 404, 500, or any other error happens, rather than showing the standard error pages that we've all seen a million times.  All the cool kids do this, for example: https://github.com/adsfas
